[package]
name = "todo_list"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = "0.5.1"
config = "0.15.8"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
sqlx = { version = "0.8.3", features = ["postgres", "runtime-tokio"]}